version: '3.8'
services:
  java-maven-app:
#    image: jcmeunier77/bootcamp-java-maven-app:jma-4.0
    image: ${IMAGE}
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd
